[TECH-554] Do not reassign ticket
Vandebron/mpyl pull request #202
Opened 2023-08-30 14:09 UTC by koeves

branch: feature/TECH-554_do_not_reassign_jira_tickets

2023-08-30 14:36 UTC, koeves commented
@SamTheisens

2023-08-30 14:36 UTC, koeves commented
@SamTheisens

2023-08-30 15:37 UTC, koeves commented on src/mpyl/reporting/targets/jira.py
> -    def __assign_ticket(self, run_user_email: str, ticket: JiraTicket):
Remember when you asked why Sam is reassigning the tickets? Well because of this

2023-08-30 15:37 UTC, koeves commented on src/mpyl/reporting/targets/jira.py
> -    def __assign_ticket(self, run_user_email: str, ticket: JiraTicket):
I don't like this feature necessarily, because running a pipeline doesn't mean you're the assignee of a ticket

2023-08-30 16:09 UTC, Jorg88 commented on src/mpyl/reporting/targets/jira.py
> -    def __assign_ticket(self, run_user_email: str, ticket: JiraTicket):
Not liking the feature is a different discussion, I kinda do like it actually. Maybe only do so when the ticket is not assigned yet?

2023-08-30 16:14 UTC, koeves commented on src/mpyl/reporting/targets/jira.py
> -    def __assign_ticket(self, run_user_email: str, ticket: JiraTicket):
hm yeah that's a middle ground I guess

2023-08-30 16:23 UTC, Jorg88 approved these changes

2023-08-30 16:24 UTC, Jorg88 commented on src/mpyl/reporting/targets/jira.py
> -    def __assign_ticket(self, run_user_email: str, ticket: JiraTicket):
simple change it seems!

2023-08-31 01:28 UTC, SamTheisens requested changes
Is this an outdated ticket perhaps? Because we used to *re*assign tickets in the past. Now only assign unassigned tickets.
It's possible that a person that hasn't implemented the ticket is the first one to kick off a build. But the scenario in which you start to work on a ticket and you forget to assign the ticket to yourself seems way more likely.

The build going unstable _does_ seem like something that needs addressing and I know we've had that issue in the past. But does it still happen?

2023-08-31 01:28 UTC, SamTheisens commented on src/mpyl/reporting/targets/jira.py
> +            if user_email and not ticket.user_email:
`ticket.user_email` signifies the reporter or creator of the ticket. That's always set.
The current logic should already only assign unassigned tickets:
https://github.com/Vandebron/mpyl/blob/f325b7b152ab86f536bd7656f8a13f8176838037/src/mpyl/reporting/targets/jira.py#L238-L239

2023-08-31 07:05 UTC, koeves commented
> Is this an outdated ticket perhaps? Because we used to _re_assign tickets in the past. Now only assign unassigned tickets. It's possible that a person that hasn't implemented the ticket is the first one to kick off a build. But the scenario in which you start to work on a ticket and you forget to assign the ticket to yourself seems way more likely.
> 
> The build going unstable _does_ seem like something that needs addressing and I know we've had that issue in the past. But does it still happen?

Okay I looked into the problem more, this problem happened to Laura because they refer to an epic in their branch and then merge every ticket into this main branch for the epic. And an epic can not be assigned.

Still in these cases the JiraReporter returns Output(success=False), so that's why the pipeline is marked as unstable (which is correct based on the output). Maybe we should swallow the failure if the assigning fails?

2023-08-31 07:23 UTC, Jorg88 commented
The ticket object doesn't have anything to indentify it as an epic?

2023-08-31 07:24 UTC, SamTheisens commented
> The ticket object doesn't have anything to identify it as an epic?

Yeah, it probably does.

2023-08-31 07:48 UTC, Jorg88 commented
> > The ticket object doesn't have anything to identify it as an epic?
> 
> Yeah, it probably does.

Then I prefer checking for that instead of swallowing the all errors! We specifically implemented marking the build as unstable last week instead of failing the pipeline for this reason -> so that we still see when stuff breaks.

2023-08-31 08:07 UTC, SamTheisens commented
> > > The ticket object doesn't have anything to identify it as an epic?
> > 
> > 
> > Yeah, it probably does.
> 
> Then I prefer checking for that instead of swallowing the all errors! We specifically implemented marking the build as unstable last week instead of failing the pipeline for this reason -> so that we still see when stuff breaks.

Maybe you could check this field: https://github.com/Vandebron/mpyl/blob/0fddb812302e5f805a745f6135d2597408a8000d/tests/reporting/targets/test_resources/jira_issue.json#L137

2023-09-04 04:32 UTC, SamTheisens approved these changes

2023-09-04 04:32 UTC, SamTheisens commented on releases/README.md
> +
I guess these release notes aren't related this PR. But I personally don't mind.

2023-09-04 13:02 UTC, merged