fix/FTS 691 github check character limit
Vandebron/mpyl pull request #292
Opened 2023-11-01 11:52 UTC by koeves

- Do not report individual test cases
- Update reporting

2023-11-01 11:59 UTC, Jorg88 approved these changes

2023-11-01 12:09 UTC, lauraoneasca approved these changes

2023-11-01 18:07 UTC, Jorg88 requested changes

2023-11-01 18:07 UTC, Jorg88 commented on src/mpyl/reporting/targets/jira.py
> +        if ticket.status_name == "To Do" and ticket.issue_type == "Epic":
```suggestion
        if ticket.status_name == "To Do" and ticket.issue_type != "Epic":
```

2023-11-02 08:07 UTC, koeves commented on src/mpyl/reporting/targets/jira.py
> +        if ticket.status_name == "To Do" and ticket.issue_type == "Epic":
whoops

2023-11-02 08:11 UTC, Jorg88 approved these changes

2023-11-02 14:32 UTC, Jorg88 approved these changes

2023-11-02 14:32 UTC, Jorg88 commented on releases/notes/1.4.1.md
> +- fix project overlays (merging children projects with their parent)
```suggestion
- Fix project overlays (merging children projects with their parent)
```

2023-11-02 14:38 UTC, merged